### ISSUE TITLE
CI unit testing for MATLAB

### ISSUE THREAD

**Issue by ryancoe** [SNL-WaterPower/WecOptTool#97]
Let's discuss the cost/benefit of setting up CI with the unit tests as has been done for MHKit.

@zmorrell-sand - Can you lay out the process (or point us to something that does)?

**Comment by ryancoe** [comment]
@zmorrell-sand - Is your existing CI machine using a site license or stand-alone?

**Comment by kmruehl** [comment]
@ryancoe @zmorrell-sand @H0R5E 

The current Jenkins server is using my stand-alone license, not the Sandia CEE site license. I cannot use the CEE license since the Virtual Machine (VM) is on the  Sandia Open Network (SON). FYI, My stand-alone license is expiring, and I plan to renew it, but also buy a separate license for Jenkins on the VM. When I purchase the second license for Jenkins I can add the Optimization Toolbox. Is that the only required package?

**Comment by kmruehl** [comment]
@ryancoe  
> 
> @zmorrell-sand - Thanks for the info. Would you be able to execute the solution you've outlined? Also, did you look at using [MATLAB Online](https://www.mathworks.com/products/matlab-online.html) to run tests (I don't see anything about this from some quick Googles)?

We looked into this, it was not a viable solution ~6 months ago, but things change

**Comment by H0R5E** [comment]
Closed with #199
